version: '3'
services:
  my-home:
    build:
      context: my-home
    ports:
      - 4000:4000
    environment:
      IOTA_PROVIDER: http://node01.testnet.iotatoken.nl:16265
      IOTA_MIN_WEIGHT_MAGNITUDE: 10
  service-provider:
    build:
      context: service-provider
    ports:
      - 5000:5000
    environment:
      IOTA_PROVIDER: http://node01.testnet.iotatoken.nl:16265
      IOTA_MIN_WEIGHT_MAGNITUDE: 10
  raspberry-pi-client:
    build:
      context: raspberry-pi-client
    # uncomment below lines and change to P1 USB port for serial port mapping
    # devices:
    #   - "/dev/tty.usbserial-AC2F18XB:/dev/USB_SERIAL_PORT"
    environment:
      IOTA_PROVIDER: http://node01.testnet.iotatoken.nl:16265
      IOTA_MIN_WEIGHT_MAGNITUDE: 10
      P1_SERIAL_PORT: /dev/USB_SERIAL_PORT
